### ISSUE TITLE
Error in "Let us return..."

### ISSUE THREAD

**Issue by mcparadip** [drsam94/Spl#10]
This is my code:

```
.
Ajax,.
Puck,.

Act I:

Scene I:
[Enter Ajax and Puck]

Puck:
Listen to thy heart!

Scene II:

Ajax:
You is the sum of thyself and a cat!
Is you better than me?
If not, let us proceed to Scene III.
Is the sum of the remainder of the quotient of you and me as good as nothing?
If not, let us proceed to Scene IV.
Let us return to Scene II.

Scene III:

Ajax:
You cat!
Open thy heart!

Scene IV:

Ajax:
You fat cat!
Open thy heart!

[Exeunt]
```

It's telling me `Ill-formed Expression in [] at line 22`.

Can you please look into this?

**Comment by mcparadip** [comment]
If I remove the line

```
Let us return to Scene II.
```

then it works fine

**Comment by drsam94** [comment]
I am willing to admit that my code yields terrible error messages, but I tried debugging this and it looks like an error with your code

`Is the sum of the remainder of the quotient of you and me as good as nothing?`

Makes no sense, if you try to build the expression tree, its

(you % me)  + [] > nothing

That is, there is no second argument for the sum. If I replace this sentence with `Is the sum of the remainder of the quotient of you and me and me as good as nothing?` the code compiles.

**Comment by mcparadip** [comment]
Ohhh, thanks!
