### ISSUE TITLE
Feature request: "with" for sums and "without" for differences

### ISSUE THREAD

**Issue by erzoe** [drsam94/Spl#14]
The readme says "If the goal of Shakespeare is to make programs look like plays, then it is sub-optimal having to use words like 'square root' all over the place" and I very much agree with that.
I'm not sure whether this is what you meant with "I may add a way to define equivalent words for math functions in a text file." but I would like to propose an alternative wording for sums and differences:

- using `with` instead of `sum`
- and `without` instead of `difference`

So for example I would like to write

    You are as lovely as the clearest warm peaceful summer's day without Hamlet.

instead of

    You are as lovely as the difference between the clearest warm peaceful summer's day and Hamlet.

Also it would be very useful if it was possible to have more than two operands:

    You are as charming as a brave handsome noble hero with a red rose and a cunning cute squirrel.

instead of

    You are as charming as the sum of a brave handsome noble hero and the sum of a red rose and a cunning cute squirrel.

**Comment by drsam94** [comment]
Ultimately, the purpose of this project is to replicate the original Shakespeare programming language as it was initially specified, with only minor bugfixes or other quality of life changes from the original language specification. If you would like to fork the repo and add language features, feel free to, but I have no intention of doing anything more than bug fixes in this repo at this time (if that)
