### ISSUE TITLE
Error with an empty expression. 

### ISSUE THREAD

**Issue by yhoyhoj** [drsam94/Spl#7]
Sorry, this look more like a Stackoverflow question than a Github issue but I am at the point where I wonder if it's not a problem with the compiler. Could you take a look ?

The compiler shows an error but I don't understand what the problem is:
The error is : `Ill-formed Expression in [] at line 40`.
Here is the code of the scene, the line 40 is the blank line before `[Exit Beatrice]`. It effectively is a blank line but why is it invalid ?

```Shakespeare
     Scene II: The argument.
 
 [Enter Dionyza and Beatrice]
 
 Beatrice:
  You are as disgusting as the product of a giant devil leech and the product of Angelo and Cassandra.
  You the difference between the square of me and thyself!
 
 [Exit Beatrice]
 
 [Enter Angelo]
 
 Dionyza:
  Am I better than a codpiece ?
 
 Angelo:
  If so, let us proceed to scene III.
 
 Dionyza:
  Am I as important as nothing ?
 
 Angelo:
  If so, let us proceed to scene IV.
  Open your heart !
 
 [Exeunt]
```

**Comment by drsam94** [comment]
I will try to take a look and debug this more thoroughly later, but just
glancing I believe the issue may be in your second sentence: "You the
difference..."; I think you probably need a form of to be in that sentence
("You are the difference...")

If that is not the issue, I can look into this farther later.

Also I will admit that if this is the issue, it is a sign that the compiler
has very poor error reporting, which is a known issue.

**Comment by yhoyhoj** [comment]
Thank you for replying this fast !
Unluckily, adding a verb ("are") didn't help. This type of sentence (without verb) can be found in the [standard](http://shakespearelang.sourceforge.net/report/shakespeare/shakespeare.html#SECTION00045000000000000000) and apparently you have made the compiler able to compile that.
If you want I can post the entire code as a Gist.

**Comment by drsam94** [comment]
The issue had to do with a bug with how the compiler detected "as" in assignments. It searched for "as" in the input, instead of " as ", causing the name Cassandra to be seen as an instance of "as".

I fixed this bug and committed the change.
