### ISSUE TITLE
Reference documentation

### ISSUE THREAD

**Issue by Neozaru** [drsam94/Spl#8]

**Comment by drsam94** [comment]
Hello, do you want to be any more specific with what sort of documentation you want?

The README references the original language specification at

http://shakespearelang.sourceforge.net/report/shakespeare/

Miles Zimmerman's

https://docs.google.com/document/d/148Qc8dMrEVcnLs2dd-ZHyR7Kl7MeWlR-vTewY4Zr6wE/edit

also has a lot of informaiton on SPL.

**Comment by drsam94** [comment]
I don't anything is really going to happen with this, so I am just going to go ahead and close this issue.
